name: personal_website
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  animated_text_kit: ^4.2.1
  google_fonts: ^2.2.0
  link:
    git: https://github.com/SaudElabdullah/link.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
flutter:
  uses-material-design: true
  assets:
    - assets/myself.jpeg